development:
  adapter: postgresql
  encoding: utf8
  database: preeventualist

test:
  adapter: sqlite3
  encoding: utf8
  database: db/test.db

production:
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  database: sinatra-template